name: Publish Docker
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        name: thinkn/private
        tags: erpnext-distera.com
        default_branch: distera.com
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        buildargs: mysqlPass=${{ secrets.ERPNEXT_MYSQL_PW }}, adminPass=${{ secrets.ERPNEXT_SETUP_PW }}
